# © Phanisment | 2024
# Thanks for download this Plugin, if you has
# questions or error, just ask me in discord.

# Discord: https://discord.com/invite/grJCgRHKvg

Disable_Vanilla_System:
  Disable_Totem_Function: true
  Disable_Evoker_Drop: true

Custom_System:
  Totem_of_Undying:
    Enable: true
    Add_Health: 2.0
    Max_Health: 20.0
    Max_Usage_Per_Hours: 3 # set 0 to disable.
  Evoker_Drops:
    Enable: true
    Chance: 0.1
    # Custom Item is next update(mybe).
  Health_System:
    Enable: true
    Reduce_Health: 2.0
    Force_Health: # Use this if you use Plugin AuraSkill.
      Enable: false
      Max_Health: 20.0

System_Message:
  Max_Use_Totem: "&4&lBRUTAL &4&l/&r You can't use Totem of Undying more than 20 Health Point."
  Max_Usage_Totem: "&4&lBRUTAL &4&l/&r Your daily Totem of Undying usage is max, try again tomorrow." # If you use daily restart