name: ${project.name}
author: Phanisment
main: io.phanisment.brutal.HealthSystem
description: Remake of Health System in Brutal Legends
version: ${project.version}
commands:
  hsreload:
    permission: healthsystem.admin
    description: Reload Plugin
    usage: /hsreload